### ISSUE TITLE
when setup harborclient,the command "docker-compose up -d " not work

### ISSUE THREAD

**Issue by 272909106** [int32bit/python-harborclient#1]
i setup harborclient,
run docker-compose up -d 
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.6.1,<2.8

**Comment by int32bit** [comment]
Setup `harborclient`  no need to run `docker-compose`, I suggest you using docker to run harborclient that won't affect your host environment.

You can easily to get the image:

```
docker pull krystism/harborclient
```

Then run in Docker:

```
docker run \
 -e HARBOR_USERNAME="admin" \
 -e HARBOR_PASSWORD="Harbor12345" \
 -e HARBOR_URL="http://192.168.56.4" \
 --net host --rm krystism/harborclient user-list
```

You can try it above, and wait for your feedback, thx.

**Comment by 272909106** [comment]
@int32bit  ,
i used docker images,it is worked.
your examples :user-change-password,how to use?
like "harbor user-change-password --username jinxj --password Harbor12345"  ?but not correct.

**Comment by int32bit** [comment]
I am not sure whether harbor API update or not, it work on my host.
