### ISSUE TITLE
Error parsing:  Project name python-harborclient was given, but was not able to be found

### ISSUE THREAD

**Issue by DavidRodHub** [int32bit/python-harborclient#10]
### Downloaded the lasted stuff. Did the following
  $ wget https://github.com/int32bit/python-harborclient/archive/master.zip
  $ cd python-harborclient-master
  $ docker build -t  myuser/harborclient .

### Got the following error:

Removing intermediate container 4d7de44b27bd
 ---> 653d905e9a67
Step 5/6 : RUN set -ex         && cd /opt/harborclient         && python setup.py install         && rm -rf /opt/harborclient
 ---> Running in 4750423d952e
+ cd /opt/harborclient
+ python setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python2.7/site-packages/pbr/util.py", line 258, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/local/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/local/lib/python2.7/site-packages/pbr/packaging.py", line 816, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name python-harborclient was given, but was not able to be found.
error in setup command: Error parsing /opt/harborclient/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name python-harborclient was given, but was not able to be found.
The command '/bin/sh -c set -ex         && cd /opt/harborclient         && python setup.py install         && rm -rf /opt/harborclient' returned a non-zero code: 1

**Comment by int32bit** [comment]
Pip may use latest git tag or branch name as distribute version,  `wget`  master branch may lose all these info. I suggest you clone this whole project using git as follows:

```
git clone https://github.com/int32bit/python-harborclient.git
cd python-harborclient
```

**Comment by DavidRodHub** [comment]
The clone worked.  Thanks for your support
